// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCH_kZgzkMFiz7chvrfRcTfqQHQcRaXxM',
    appId: '1:15908717565:web:934863adbd60a797b70f94',
    messagingSenderId: '15908717565',
    projectId: 'fir-bank-c0bad',
    authDomain: 'fir-bank-c0bad.firebaseapp.com',
    storageBucket: 'fir-bank-c0bad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-9quT3lzGPQaAPBJIovOMMVfDjyTFI4',
    appId: '1:15908717565:android:138b99b9182c5b1cb70f94',
    messagingSenderId: '15908717565',
    projectId: 'fir-bank-c0bad',
    storageBucket: 'fir-bank-c0bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmhhL2UP5c8BAN63UHgFPQuTs-enPpPY4',
    appId: '1:15908717565:ios:01153755900356afb70f94',
    messagingSenderId: '15908717565',
    projectId: 'fir-bank-c0bad',
    storageBucket: 'fir-bank-c0bad.firebasestorage.app',
    iosBundleId: 'com.example.demoBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmhhL2UP5c8BAN63UHgFPQuTs-enPpPY4',
    appId: '1:15908717565:ios:01153755900356afb70f94',
    messagingSenderId: '15908717565',
    projectId: 'fir-bank-c0bad',
    storageBucket: 'fir-bank-c0bad.firebasestorage.app',
    iosBundleId: 'com.example.demoBank',
  );
}
